"""Generate downloadable PDF scan reports using ReportLab."""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


RISK_COLOR_MAP = {
    "safe": colors.HexColor("#00FF9C"),
    "suspicious": colors.HexColor("#FFB020"),
    "high_risk": colors.HexColor("#FF4757"),
}


def generate_scan_report_pdf(
    scan: Dict[str, Any],
    results: List[Dict[str, Any]],
) -> bytes:
    """Build a PDF summarizing scan metadata and per-package results."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=20,
        spaceAfter=12,
        textColor=colors.HexColor("#0D1117"),
    )
    body = styles["Normal"]
    story = []

    story.append(Paragraph("PackGuard Security Scan Report", title_style))
    story.append(Spacer(1, 0.2 * inch))

    scan_id = scan.get("scanId", "unknown")
    created = scan.get("createdAt")
    created_str = (
        created.isoformat() if isinstance(created, datetime) else str(created or "N/A")
    )
    story.append(Paragraph(f"<b>Scan ID:</b> {scan_id}", body))
    story.append(Paragraph(f"<b>Type:</b> {scan.get('type', 'N/A')}", body))
    story.append(Paragraph(f"<b>Created:</b> {created_str}", body))
    story.append(
        Paragraph(
            f"<b>Overall Risk:</b> {scan.get('overallRiskLevel', 'N/A')}", body
        )
    )
    story.append(Spacer(1, 0.3 * inch))

    for result in results:
        pkg = result.get("packageName", "unknown")
        version = result.get("packageVersion", "unknown")
        risk_level = result.get("riskLevel", "unknown")
        risk_score = result.get("riskScore", 0)

        story.append(Paragraph(f"<b>{pkg}=={version}</b>", styles["Heading2"]))
        story.append(
            Paragraph(
                f"Risk Score: {risk_score}/100 — Level: {risk_level.replace('_', ' ').title()}",
                body,
            )
        )

        reasons = result.get("flaggedReasons") or []
        explanation = result.get("explanation") or []
        messages = [r.get("message", "") for r in reasons] or explanation

        if messages:
            story.append(Paragraph("<b>Findings:</b>", body))
            for msg in messages:
                story.append(Paragraph(f"• {msg}", body))

        known_vulns = result.get("knownVulnerabilities") or result.get("known_vulnerabilities") or []
        if known_vulns:
            story.append(Spacer(1, 0.08 * inch))
            story.append(Paragraph("<b>Known Vulnerabilities (OSV.dev):</b>", body))
            for v in known_vulns:
                cve_id = v.get("cve_id") or v.get("cveId", "CVE")
                sev = v.get("severity", "UNKNOWN")
                summary = v.get("summary", "")
                fix = v.get("fixed_version") or v.get("fixedVersion")
                fix_str = f" [Fix: &gt;={fix}]" if fix else ""
                story.append(Paragraph(f"• <b>{cve_id}</b> ({sev}){fix_str}: {summary}", body))

        features = result.get("staticAnalysisFeatures") or {}
        if features:
            rows = [["Feature", "Detected"]]
            for key, val in features.items():
                if key == "suspiciousUrls":
                    val_str = ", ".join(val) if val else "None"
                else:
                    val_str = "Yes" if val else "No"
                rows.append([key, val_str])

            table = Table(rows, colWidths=[3 * inch, 2.5 * inch])
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0D1117")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ]
                )
            )
            story.append(Spacer(1, 0.1 * inch))
            story.append(table)

        story.append(Spacer(1, 0.25 * inch))

    story.append(
        Paragraph(
            "<i>Generated by PackGuard — static analysis only; package code is never executed.</i>",
            styles["Italic"],
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
