"""
slopsquat_detector.py
======================
Heuristic detection of potential AI-hallucination slopsquatting packages on PyPI.

METHODOLOGY NOTE (IEEE Paper Context):
--------------------------------------
This module implements a bounded, honest heuristic proxy for identifying packages
vulnerable to or intentionally registered as "slopsquatting" targets (packages
hallucinated by Large Language Models such as ChatGPT, Copilot, or Claude and
subsequently registered by attackers to hijack developer copy-paste behavior).

True hallucination detection requires observing live LLM generation outputs or
continually querying proprietary model endpoints. In contrast, this detector operates
strictly offline and heuristically (`detection_method: "heuristic_proxy"`), combining:
1. Heuristic Pattern Scoring: Syntactic resemblance to common AI code generation
   conventions (e.g. `<library>-utils`, `<library>-helper`, `py<library>`) combined
   with recent publication recency and low download volumes.
2. Curated Incident Knowledge Base: Exact and near-match lookup against documented
   hallucination-squatting incidents from public security research.

This design is deliberately scoped as a heuristic approximation for supply-chain risk
triaging, avoiding false claims of verified LLM-hallucination detection.
"""

from __future__ import annotations

import json
import logging
import os
from functools import lru_cache
from typing import Any, Dict, List, Optional, Set, Tuple

from app.services.typosquat.top_packages import get_trusted_packages

logger = logging.getLogger(__name__)

DETECTION_METHOD: str = "heuristic_proxy"

# Standard affixes commonly generated by LLMs when hallucinating non-existent helpers
SLOPSQUAT_SUFFIXES: Tuple[str, ...] = (
    "-utils",
    "-helper",
    "-helpers",
    "-tools",
    "-tool",
    "-ext",
    "-extension",
    "-client",
    "-core",
    "-api",
    "-wrapper",
    "-sdk",
    "-common",
    "-contrib",
    "_utils",
    "_helper",
    "_tools",
    "_client",
)

SLOPSQUAT_PREFIXES: Tuple[str, ...] = (
    "py-",
    "py_",
    "python-",
    "python_",
    "ai-",
    "py",
)

# Minimum confidence required to flag as a possible slopsquat
SLOPSQUAT_CONFIDENCE_THRESHOLD: int = 50


def _compute_levenshtein(a: str, b: str) -> int:
    """Standard Levenshtein distance between two strings."""
    if a == b:
        return 0
    if not a:
        return len(b)
    if not b:
        return len(a)
    dp = list(range(len(b) + 1))
    for i, ca in enumerate(a):
        new_dp = [i + 1] * (len(b) + 1)
        for j, cb in enumerate(b):
            cost = 0 if ca == cb else 1
            new_dp[j + 1] = min(
                dp[j + 1] + 1,      # deletion
                new_dp[j] + 1,      # insertion
                dp[j] + cost,       # substitution
            )
        dp = new_dp
    return dp[len(b)]


def get_default_curated_data_path() -> str:
    """Resolve default path to known_hallucinated_packages.json."""
    current_dir = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(current_dir, "..", "data", "known_hallucinated_packages.json"),
        os.path.join(current_dir, "known_hallucinated_packages.json"),
        os.path.join(os.getcwd(), "app", "data", "known_hallucinated_packages.json"),
    ]
    for candidate in candidates:
        if os.path.exists(candidate):
            return os.path.abspath(candidate)
    return candidates[0]


@lru_cache(maxsize=1)
def load_known_hallucinated_packages(file_path: Optional[str] = None) -> List[Dict[str, Any]]:
    """Load curated list of documented hallucinated package research targets."""
    path = file_path or get_default_curated_data_path()
    if not os.path.exists(path):
        logger.warning("Curated hallucinated packages list not found at: %s", path)
        return []

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            return data
        return []
    except Exception:
        logger.exception("Failed loading curated hallucinated packages from %s", path)
        return []


def extract_slopsquat_pattern(package_name: str) -> Tuple[Optional[str], Optional[str], Optional[str]]:
    """
    Check if a package name matches common AI/coding naming conventions.

    Returns:
        (base_library_name, affix_matched, affix_type: 'suffix' | 'prefix')
        or (None, None, None) if no pattern matches.
    """
    normalized = package_name.strip().lower()

    # Suffix check takes precedence (e.g. requests-utils, flask-helper)
    for suffix in SLOPSQUAT_SUFFIXES:
        if normalized.endswith(suffix):
            base = normalized[:-len(suffix)].strip("-_")
            if base:
                return base, suffix, "suffix"

    # Prefix check (e.g. pyrequests, py-jwt)
    for prefix in SLOPSQUAT_PREFIXES:
        if normalized.startswith(prefix):
            base = normalized[len(prefix):].strip("-_")
            # Require base length >= 3 to avoid splitting very short names (e.g., 'pi' -> 'i')
            if len(base) >= 3:
                return base, prefix, "prefix"

    return None, None, None


def check_curated_list(
    package_name: str,
    curated_list: Optional[List[Dict[str, Any]]] = None,
) -> Optional[Tuple[bool, int, str]]:
    """
    Check package name against curated documented hallucination incidents.

    Returns (is_match, confidence, reason) or None if no match.
    """
    entries = curated_list if curated_list is not None else load_known_hallucinated_packages()
    if not entries:
        return None

    normalized_pkg = package_name.strip().lower().replace("_", "-")

    # 1. Exact match check
    for entry in entries:
        curated_name = str(entry.get("package_name", "")).strip().lower().replace("_", "-")
        if normalized_pkg == curated_name:
            source = entry.get("source_research", "Security Research")
            desc = entry.get("description", "Documented AI-hallucination target")
            target = entry.get("target_library", "")
            target_str = f" for '{target}'" if target else ""
            reason = (
                f"Matches documented AI-hallucination slopsquatting incident '{curated_name}'{target_str} "
                f"({source}): {desc} [Method: heuristic_proxy]"
            )
            return True, 95, reason

    # 2. Near-match check (edit distance 1, or 2 for longer names)
    for entry in entries:
        curated_name = str(entry.get("package_name", "")).strip().lower().replace("_", "-")
        dist = _compute_levenshtein(normalized_pkg, curated_name)
        max_dist = 2 if len(curated_name) >= 12 else 1
        if 1 <= dist <= max_dist:
            source = entry.get("source_research", "Security Research")
            reason = (
                f"Near-match (Levenshtein distance {dist}) to documented AI hallucination incident "
                f"'{curated_name}' ({source}) [Method: heuristic_proxy]"
            )
            return True, 80, reason

    return None


def detect_slopsquat(
    package_name: str,
    days_since_first_publish: Optional[float] = None,
    download_count: Optional[int] = None,
    maintainer_count: Optional[float] = None,
    curated_data_path: Optional[str] = None,
    trusted_packages: Optional[Set[str]] = None,
) -> Dict[str, Any]:
    """
    Evaluates whether a package is a potential AI-hallucination slopsquatting target.

    Combines:
    1. Curated incident lookup (exact and near-matches from documented research).
    2. Weighted heuristic signal (AI convention naming + recency + low downloads).

    Returns:
        {
            "is_possible_slopsquat": bool,
            "confidence": int (0-100),
            "reason": str,
            "detection_method": "heuristic_proxy",
            "isPossibleSlopsquat": bool,
            "detectionMethod": "heuristic_proxy"
        }
    """
    normalized_pkg = package_name.strip().lower().replace("_", "-")
    trusted = trusted_packages if trusted_packages is not None else get_trusted_packages()

    # Safety check: Established top packages cannot be slopsquats of themselves
    if normalized_pkg in trusted:
        return {
            "is_possible_slopsquat": False,
            "confidence": 0,
            "reason": f"Package '{package_name}' is a verified established top PyPI package.",
            "detection_method": DETECTION_METHOD,
            "isPossibleSlopsquat": False,
            "detectionMethod": DETECTION_METHOD,
        }

    # Check 1: Curated list check (documented incidents take precedence)
    curated_entries = load_known_hallucinated_packages(curated_data_path)
    curated_match = check_curated_list(package_name, curated_entries)
    if curated_match is not None:
        is_match, conf, reason = curated_match
        return {
            "is_possible_slopsquat": is_match,
            "confidence": conf,
            "reason": reason,
            "detection_method": DETECTION_METHOD,
            "isPossibleSlopsquat": is_match,
            "detectionMethod": DETECTION_METHOD,
        }

    # Check 2: Heuristic proxy scoring
    base_lib, affix, affix_type = extract_slopsquat_pattern(package_name)
    if not base_lib:
        return {
            "is_possible_slopsquat": False,
            "confidence": 0,
            "reason": "Package name does not match common AI-hallucination naming patterns.",
            "detection_method": DETECTION_METHOD,
            "isPossibleSlopsquat": False,
            "detectionMethod": DETECTION_METHOD,
        }

    confidence = 0
    signals: List[str] = []

    # Syntactic pattern signal: matches AI conventions
    confidence += 30
    signals.append(f"AI naming pattern ({affix_type} '{affix}')")

    # Target library signal: base name is a popular/trusted package
    base_normalized = base_lib.replace("_", "-")
    if base_normalized in trusted:
        confidence += 30
        signals.append(f"targets popular library '{base_normalized}'")
    else:
        # Base library is not in top-5000, smaller weight
        confidence += 10
        signals.append(f"targets component '{base_normalized}'")

    # Recency signal: recently first published on PyPI
    if days_since_first_publish is not None:
        if days_since_first_publish <= 90:
            confidence += 20
            signals.append(f"recently published ({int(days_since_first_publish)} days old)")
        elif days_since_first_publish <= 180:
            confidence += 10
            signals.append(f"moderately recent ({int(days_since_first_publish)} days old)")
        elif days_since_first_publish > 730:
            # Established package published over 2 years ago: decrease suspicion
            confidence = max(0, confidence - 25)
            signals.append("mature package (> 2 years old)")
    else:
        # If publish age unavailable, add small neutral default recency assumption
        confidence += 10

    # Download volume signal
    if download_count is not None:
        if download_count < 1000:
            confidence += 15
            signals.append(f"low download volume ({download_count} downloads)")
        elif download_count > 50000:
            confidence = max(0, confidence - 30)
            signals.append(f"high adoption ({download_count} downloads)")
    else:
        # Many slopsquats have virtually zero adoption
        confidence += 10
        signals.append("low/untracked download count")

    # Maintainer signal
    if maintainer_count is not None and maintainer_count <= 1:
        confidence += 5
        signals.append("single maintainer account")

    # Bound confidence to 0-100 range
    confidence = max(0, min(100, confidence))
    is_slopsquat = confidence >= SLOPSQUAT_CONFIDENCE_THRESHOLD

    if is_slopsquat:
        reason = (
            f"Heuristic proxy signals ({confidence}% confidence): {', '.join(signals)}. "
            f"Bounded approximation of potential AI-hallucination target [Method: {DETECTION_METHOD}]."
        )
    else:
        reason = (
            f"Heuristic proxy confidence ({confidence}%) below threshold ({SLOPSQUAT_CONFIDENCE_THRESHOLD}%): "
            f"{', '.join(signals)}."
        )

    return {
        "is_possible_slopsquat": is_slopsquat,
        "confidence": confidence,
        "reason": reason,
        "detection_method": DETECTION_METHOD,
        "isPossibleSlopsquat": is_slopsquat,
        "detectionMethod": DETECTION_METHOD,
    }
